### PR TITLE
e2c and c2e tests; fix flipped image issue mentioned in #11

### PR DESCRIPTION
**Pull request by BrianPugh**
Uses the solution posted by @zafirshi in #11. For this to fully work other spurious flips in the codebase have to be removed, which cleans things up nicely.

Certainly a breaking-change-bugfix.

Honorable mention: @moonpyx

### CODE REVIEW

**Comment by ProGamerGov** [comment]
@BrianPugh were these the only changes you made to correct the face orientation?

**Comment by BrianPugh** [comment]
> @BrianPugh were these the only changes you made to correct the face orientation?

Correct

**Comment by ProGamerGov** [comment]
@BrianPugh I tried copying these changes with my pytorch code, but confusingly the problem still remains.

**Comment by ProGamerGov** [comment]
@BrianPugh I've been playing around with it for a bit, but I might actually need your help in figuring it out.

**Pull request merged**
